services:
  - type: web
    name: student-risk-backend
    env: node
    region: singapore
    plan: free
    rootDir: ./
    buildCommand: |
      cd backend && npm install &&
      pip3 install --user scikit-learn joblib pandas numpy matplotlib mysql-connector-python python-dotenv
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: FRONTEND_URL
        sync: false
